name: monopoly
description: A monopoly game.
version: 0.0.4
authors:
- Spencer Cornish
- Keely Weisbeck
- Nate Tranel
- Bryan Plant

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  dart_dev: "^1.8.1"
  dart_style: "^1.0.8"
  coverage: "^0.9.3"
  test: "^0.12.25"
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter
- test/pub_serve:
      $include: test/**_test{.*,}.dart


# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
