@TestOn('browser')
library test.unit.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/ -e Environment.browser --genHtml`

import './src/app/app_test.dart' as src_app_app_test;
import './src/bank/bank_test.dart' as src_bank_bank_test;
import './src/board/board_test.dart' as src_board_board_test;
import './src/jail/jail_test.dart' as src_jail_jail_test;
import './src/player/player_test.dart' as src_player_player_test;
import './src/tiles/property_test.dart' as src_tiles_property_test;
import './src/tiles/railroad_test.dart' as src_tiles_railroad_test;
import './src/tiles/utility_test.dart' as src_tiles_utility_test;
import 'package:test/test.dart';

void main() {
  src_app_app_test.main();
  src_bank_bank_test.main();
  src_board_board_test.main();
  src_jail_jail_test.main();
  src_player_player_test.main();
  src_tiles_property_test.main();
  //src_tiles_railroad_test.main();
  src_tiles_utility_test.main();
}
