@TestOn('browser')
library test.generated_runner;

// Generated by `pub run dart_dev gen-test-runner -d test/ -e Environment.browser --genHtml`

import './app/app_test.dart' as app_app_test;
import './bank/bank_test.dart' as bank_bank_test;
import './board/board_test.dart' as board_board_test;
import './jail/jail_test.dart' as jail_jail_test;
import './player/player_test.dart' as player_player_test;
import './tiles/property_test.dart' as tiles_property_test;
import './tiles/railroad_test.dart' as tiles_railroad_test;
import './tiles/utility_test.dart' as tiles_utility_test;
import 'package:test/test.dart';

void main() {
  app_app_test.main();
  bank_bank_test.main();
  board_board_test.main();
  jail_jail_test.main();
  player_player_test.main();
  tiles_property_test.main();
  tiles_railroad_test.main();
  tiles_utility_test.main();
}